#!/usr/bin/env bash
# making nginx run as nginx and listen at port 8080
chown nginx: nginx /etc/nginx/nginx.conf
pkill apache2
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
